// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/login.proto

package login

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SignUpRequest struct {
	Email                string                    `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string                    `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	FirstName            string                    `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string                    `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Secret               *SignUpRequest_SecretCode `protobuf:"bytes,5,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *SignUpRequest) Reset()         { *m = SignUpRequest{} }
func (m *SignUpRequest) String() string { return proto.CompactTextString(m) }
func (*SignUpRequest) ProtoMessage()    {}
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_40fa32f243b417c0, []int{0}
}

func (m *SignUpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpRequest.Unmarshal(m, b)
}
func (m *SignUpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpRequest.Marshal(b, m, deterministic)
}
func (m *SignUpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpRequest.Merge(m, src)
}
func (m *SignUpRequest) XXX_Size() int {
	return xxx_messageInfo_SignUpRequest.Size(m)
}
func (m *SignUpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpRequest proto.InternalMessageInfo

func (m *SignUpRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignUpRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *SignUpRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *SignUpRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *SignUpRequest) GetSecret() *SignUpRequest_SecretCode {
	if m != nil {
		return m.Secret
	}
	return nil
}

type SignUpRequest_SecretCode struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Sent                 bool     `protobuf:"varint,2,opt,name=sent,proto3" json:"sent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpRequest_SecretCode) Reset()         { *m = SignUpRequest_SecretCode{} }
func (m *SignUpRequest_SecretCode) String() string { return proto.CompactTextString(m) }
func (*SignUpRequest_SecretCode) ProtoMessage()    {}
func (*SignUpRequest_SecretCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_40fa32f243b417c0, []int{0, 0}
}

func (m *SignUpRequest_SecretCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpRequest_SecretCode.Unmarshal(m, b)
}
func (m *SignUpRequest_SecretCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpRequest_SecretCode.Marshal(b, m, deterministic)
}
func (m *SignUpRequest_SecretCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpRequest_SecretCode.Merge(m, src)
}
func (m *SignUpRequest_SecretCode) XXX_Size() int {
	return xxx_messageInfo_SignUpRequest_SecretCode.Size(m)
}
func (m *SignUpRequest_SecretCode) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpRequest_SecretCode.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpRequest_SecretCode proto.InternalMessageInfo

func (m *SignUpRequest_SecretCode) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *SignUpRequest_SecretCode) GetSent() bool {
	if m != nil {
		return m.Sent
	}
	return false
}

type SignUpResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpResponse) Reset()         { *m = SignUpResponse{} }
func (m *SignUpResponse) String() string { return proto.CompactTextString(m) }
func (*SignUpResponse) ProtoMessage()    {}
func (*SignUpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_40fa32f243b417c0, []int{1}
}

func (m *SignUpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpResponse.Unmarshal(m, b)
}
func (m *SignUpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpResponse.Marshal(b, m, deterministic)
}
func (m *SignUpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpResponse.Merge(m, src)
}
func (m *SignUpResponse) XXX_Size() int {
	return xxx_messageInfo_SignUpResponse.Size(m)
}
func (m *SignUpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpResponse proto.InternalMessageInfo

func (m *SignUpResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type LogInRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogInRequest) Reset()         { *m = LogInRequest{} }
func (m *LogInRequest) String() string { return proto.CompactTextString(m) }
func (*LogInRequest) ProtoMessage()    {}
func (*LogInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_40fa32f243b417c0, []int{2}
}

func (m *LogInRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogInRequest.Unmarshal(m, b)
}
func (m *LogInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogInRequest.Marshal(b, m, deterministic)
}
func (m *LogInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogInRequest.Merge(m, src)
}
func (m *LogInRequest) XXX_Size() int {
	return xxx_messageInfo_LogInRequest.Size(m)
}
func (m *LogInRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogInRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogInRequest proto.InternalMessageInfo

func (m *LogInRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LogInRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LogInResponse struct {
	User                 *SignUpRequest `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *LogInResponse) Reset()         { *m = LogInResponse{} }
func (m *LogInResponse) String() string { return proto.CompactTextString(m) }
func (*LogInResponse) ProtoMessage()    {}
func (*LogInResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_40fa32f243b417c0, []int{3}
}

func (m *LogInResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogInResponse.Unmarshal(m, b)
}
func (m *LogInResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogInResponse.Marshal(b, m, deterministic)
}
func (m *LogInResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogInResponse.Merge(m, src)
}
func (m *LogInResponse) XXX_Size() int {
	return xxx_messageInfo_LogInResponse.Size(m)
}
func (m *LogInResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogInResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogInResponse proto.InternalMessageInfo

func (m *LogInResponse) GetUser() *SignUpRequest {
	if m != nil {
		return m.User
	}
	return nil
}

type ForgotPasswordRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgotPasswordRequest) Reset()         { *m = ForgotPasswordRequest{} }
func (m *ForgotPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ForgotPasswordRequest) ProtoMessage()    {}
func (*ForgotPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_40fa32f243b417c0, []int{4}
}

func (m *ForgotPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgotPasswordRequest.Unmarshal(m, b)
}
func (m *ForgotPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgotPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ForgotPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgotPasswordRequest.Merge(m, src)
}
func (m *ForgotPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ForgotPasswordRequest.Size(m)
}
func (m *ForgotPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgotPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForgotPasswordRequest proto.InternalMessageInfo

func (m *ForgotPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ForgotPasswordResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgotPasswordResponse) Reset()         { *m = ForgotPasswordResponse{} }
func (m *ForgotPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ForgotPasswordResponse) ProtoMessage()    {}
func (*ForgotPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_40fa32f243b417c0, []int{5}
}

func (m *ForgotPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgotPasswordResponse.Unmarshal(m, b)
}
func (m *ForgotPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgotPasswordResponse.Marshal(b, m, deterministic)
}
func (m *ForgotPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgotPasswordResponse.Merge(m, src)
}
func (m *ForgotPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ForgotPasswordResponse.Size(m)
}
func (m *ForgotPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgotPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ForgotPasswordResponse proto.InternalMessageInfo

func (m *ForgotPasswordResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*SignUpRequest)(nil), "login.SignUpRequest")
	proto.RegisterType((*SignUpRequest_SecretCode)(nil), "login.SignUpRequest.SecretCode")
	proto.RegisterType((*SignUpResponse)(nil), "login.SignUpResponse")
	proto.RegisterType((*LogInRequest)(nil), "login.LogInRequest")
	proto.RegisterType((*LogInResponse)(nil), "login.LogInResponse")
	proto.RegisterType((*ForgotPasswordRequest)(nil), "login.ForgotPasswordRequest")
	proto.RegisterType((*ForgotPasswordResponse)(nil), "login.ForgotPasswordResponse")
}

func init() { proto.RegisterFile("protos/login.proto", fileDescriptor_40fa32f243b417c0) }

var fileDescriptor_40fa32f243b417c0 = []byte{
	// 411 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x4f, 0xeb, 0xd3, 0x40,
	0x10, 0x25, 0xb5, 0xc9, 0x2f, 0x9d, 0xfe, 0x11, 0xd7, 0x54, 0x42, 0x6c, 0xb1, 0xec, 0xa9, 0x14,
	0x6c, 0x20, 0x82, 0x62, 0x4f, 0x8a, 0x28, 0x14, 0x8a, 0x94, 0x14, 0xcf, 0xb2, 0xb6, 0xdb, 0xb0,
	0x90, 0xee, 0xc6, 0xec, 0x46, 0xef, 0x5e, 0xfc, 0x00, 0x7e, 0x34, 0xbf, 0x82, 0x67, 0x3f, 0x83,
	0x64, 0xb2, 0x51, 0x5b, 0xaa, 0x82, 0xb7, 0xbc, 0x99, 0x37, 0x6f, 0xde, 0x9b, 0x24, 0x40, 0x8a,
	0x52, 0x19, 0xa5, 0xe3, 0x5c, 0x65, 0x42, 0x2e, 0x11, 0x10, 0x17, 0x41, 0x34, 0xc9, 0x94, 0xca,
	0x72, 0x1e, 0xb3, 0x42, 0xc4, 0x4c, 0x4a, 0x65, 0x98, 0x11, 0x4a, 0xea, 0x86, 0x44, 0xbf, 0x3b,
	0x30, 0xdc, 0x89, 0x4c, 0xbe, 0x29, 0x52, 0xfe, 0xbe, 0xe2, 0xda, 0x90, 0x00, 0x5c, 0x7e, 0x62,
	0x22, 0x0f, 0x9d, 0x99, 0x33, 0xef, 0xa5, 0x0d, 0x20, 0x11, 0xf8, 0x05, 0xd3, 0xfa, 0xa3, 0x2a,
	0x0f, 0x61, 0x07, 0x1b, 0x3f, 0x31, 0x99, 0x02, 0x1c, 0x45, 0xa9, 0xcd, 0x5b, 0xc9, 0x4e, 0x3c,
	0xbc, 0x85, 0xdd, 0x1e, 0x56, 0x5e, 0xb3, 0x13, 0x27, 0xf7, 0xa1, 0x97, 0xb3, 0xb6, 0xdb, 0x6d,
	0x66, 0xeb, 0x02, 0x36, 0x9f, 0x80, 0xa7, 0xf9, 0xbe, 0xe4, 0x26, 0x74, 0x67, 0xce, 0xbc, 0x9f,
	0x3c, 0x58, 0x36, 0x11, 0xce, 0x3c, 0x2d, 0x77, 0x48, 0x79, 0xa1, 0x0e, 0x3c, 0xb5, 0xf4, 0xe8,
	0x31, 0xc0, 0xaf, 0x6a, 0x6d, 0xfa, 0x03, 0xcb, 0x2b, 0xde, 0x9a, 0x46, 0x40, 0x08, 0x74, 0x35,
	0x97, 0x06, 0x0d, 0xfb, 0x29, 0x3e, 0xd3, 0x05, 0x8c, 0x5a, 0x6d, 0x5d, 0x28, 0xa9, 0x39, 0x09,
	0xe1, 0x46, 0x57, 0xfb, 0x3d, 0xd7, 0x1a, 0xa7, 0xfd, 0xb4, 0x85, 0xf4, 0x19, 0x0c, 0x36, 0x2a,
	0x5b, 0xcb, 0xff, 0x3e, 0x0d, 0x7d, 0x0a, 0x43, 0xab, 0x60, 0x97, 0xcd, 0xa1, 0x5b, 0x69, 0x5e,
	0xa2, 0x42, 0x3f, 0x09, 0xae, 0xa5, 0x4d, 0x91, 0x41, 0x1f, 0xc2, 0xf8, 0x95, 0x2a, 0x33, 0x65,
	0xb6, 0x56, 0xec, 0xaf, 0x2e, 0x68, 0x02, 0xf7, 0x2e, 0xe9, 0xff, 0xca, 0x97, 0x7c, 0xee, 0x80,
	0xbf, 0xa9, 0x0d, 0x3c, 0xdf, 0xae, 0xc9, 0x1a, 0xbc, 0xc6, 0x06, 0xb9, 0xea, 0x2a, 0x1a, 0x5f,
	0x54, 0x1b, 0x75, 0x4a, 0x3e, 0x7d, 0xfd, 0xf6, 0xa5, 0x33, 0xa0, 0x37, 0xb1, 0x16, 0x99, 0xac,
	0x8a, 0x95, 0xb3, 0x20, 0x2f, 0xc1, 0xc5, 0xd4, 0xe4, 0xae, 0x9d, 0xf9, 0xfd, 0x8a, 0x51, 0x70,
	0x5e, 0xb4, 0x3a, 0x77, 0x50, 0xa7, 0x4f, 0xbd, 0xe6, 0x1b, 0xae, 0x65, 0x04, 0x8c, 0xce, 0x23,
	0x91, 0x89, 0x1d, 0xbd, 0x7a, 0x98, 0x68, 0xfa, 0x87, 0xae, 0xdd, 0x10, 0xe1, 0x86, 0x80, 0xde,
	0x8e, 0x8f, 0x48, 0x68, 0x5f, 0xd2, 0xca, 0x59, 0xbc, 0xf3, 0xf0, 0x6f, 0x78, 0xf4, 0x23, 0x00,
	0x00, 0xff, 0xff, 0xc4, 0x5c, 0x12, 0xfe, 0x48, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LoginAPIClient is the client API for LoginAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LoginAPIClient interface {
	SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*SignUpResponse, error)
	LogIn(ctx context.Context, in *LogInRequest, opts ...grpc.CallOption) (*LogInResponse, error)
	ForgotPassword(ctx context.Context, in *ForgotPasswordRequest, opts ...grpc.CallOption) (*ForgotPasswordResponse, error)
}

type loginAPIClient struct {
	cc *grpc.ClientConn
}

func NewLoginAPIClient(cc *grpc.ClientConn) LoginAPIClient {
	return &loginAPIClient{cc}
}

func (c *loginAPIClient) SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*SignUpResponse, error) {
	out := new(SignUpResponse)
	err := c.cc.Invoke(ctx, "/login.LoginAPI/SignUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginAPIClient) LogIn(ctx context.Context, in *LogInRequest, opts ...grpc.CallOption) (*LogInResponse, error) {
	out := new(LogInResponse)
	err := c.cc.Invoke(ctx, "/login.LoginAPI/LogIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginAPIClient) ForgotPassword(ctx context.Context, in *ForgotPasswordRequest, opts ...grpc.CallOption) (*ForgotPasswordResponse, error) {
	out := new(ForgotPasswordResponse)
	err := c.cc.Invoke(ctx, "/login.LoginAPI/ForgotPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoginAPIServer is the server API for LoginAPI service.
type LoginAPIServer interface {
	SignUp(context.Context, *SignUpRequest) (*SignUpResponse, error)
	LogIn(context.Context, *LogInRequest) (*LogInResponse, error)
	ForgotPassword(context.Context, *ForgotPasswordRequest) (*ForgotPasswordResponse, error)
}

func RegisterLoginAPIServer(s *grpc.Server, srv LoginAPIServer) {
	s.RegisterService(&_LoginAPI_serviceDesc, srv)
}

func _LoginAPI_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginAPIServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/login.LoginAPI/SignUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginAPIServer).SignUp(ctx, req.(*SignUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoginAPI_LogIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginAPIServer).LogIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/login.LoginAPI/LogIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginAPIServer).LogIn(ctx, req.(*LogInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoginAPI_ForgotPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForgotPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginAPIServer).ForgotPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/login.LoginAPI/ForgotPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginAPIServer).ForgotPassword(ctx, req.(*ForgotPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LoginAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "login.LoginAPI",
	HandlerType: (*LoginAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignUp",
			Handler:    _LoginAPI_SignUp_Handler,
		},
		{
			MethodName: "LogIn",
			Handler:    _LoginAPI_LogIn_Handler,
		},
		{
			MethodName: "ForgotPassword",
			Handler:    _LoginAPI_ForgotPassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/login.proto",
}
